### ISSUE TITLE
Stop Deleting my work

### ISSUE THREAD

**Issue by MiroTheSuperDev** [MCrafterss/MTeamPvP#1]
hey it was my idea and i was going to start on it today it is not funny to delete others work

**Comment by CraftingMania** [comment]
i will make my plugins on my profile now and fork it thx to you note if you did this one more time i will be very sad

**Comment by MiroTheSuperDev** [comment]
oh sorry taha i thought mine was deleted sorry

**Comment by TahaTheHacker** [comment]
-_-
