### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by HittmanA** [MCrafterss/MTeamPvP#15]

**Comment by ghost** [comment]
Download zip and extract it
Copy the extracted folder and paste it in plugins/ folder
Install Devtools (If you don't have)
Start the server

**Comment by MiroTheSuperDev** [comment]
currently we are having some problems in the plugin so we will be trying to fix it

**Comment by MiroTheSuperDev** [comment]
you got the block location you want your sign to be placed into or your blue or red team be into then write that in config.yml

but you must place the sign first in that location before writing it to config.yml

**Comment by MiroTheSuperDev** [comment]
also if you need support with the plugin we offer 100% free support for our open source plugins just go to http://forums.mcrafters.ml

then register an account 

press on support tickets 

then post your ticket

a team member will handle the ticket and help you set up the plugin
