### ISSUE TITLE
Could not locate the given world name on the config.yml

### ISSUE THREAD

**Issue by drgimatt** [MCrafterss/MTeamPvP#18]
This is the issue that I am getting once I turn on my server:

[20:50:55] system> Enabling MTeamPvP v1.0.0 Beta

Warning: yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 7, column 11) in phar://C:/Users/MIXUEL/Desktop/ImagicalMine/ImagicalMine.phar/src/pocketmine/utils/Config.php on line 158

Notice: Undefined index: sign_world in C:\Users\MIXUEL\Desktop\ImagicalMine\plugins\MTeamPvP-master\src\MCrafters\TeamPvP\TeamPvP.php on line 43
[20:50:55] error> [MTeamPvP] The level you used on the config (  ) doesn't exist! stopping plugin...
[20:50:55] system> Disabling MTeamPvP v1.0.0 Beta
[20:50:55] critical> pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1216

This is my config file currently

---
# the positions of the join sign

sign_join_x:1320
sign_join_y:76
sign_join_z:1041
sign_world: "TeamPVP"
# the positions of the team's enter places.

blue_enter_x: 1299
blue_enter_y: 33
blue_enter_z: 1010

red_enter_x: 1319
red_enter_y: 37
red_enter_z: 1041
# the place when players teleport when the game is going to start soon

waiting_x: 1320
waiting_y: 63
waiting_z: 1040
# the items will be given to the players when the game starts

items:
- 276
- 3
# the message will be sent to the player when he's hitting his team mate

hit_same_team_message: "{player} is in your team!"
# the message will be sent to the player when the teams are full

teams_are_full_message: "Teams are full"
# the level that we'll get it's spawn and teleport the player to it when the game ends

spawn_level: "TeamPVP"
...

**Comment by MiroTheSuperDev** [comment]
because you need to have that world in your worlds folder

**Comment by MiroTheSuperDev** [comment]
and it must be exactly have the same name as config.yml 

and the same caps 

in the folder name

**Comment by drgimatt** [comment]
I do have the world in my worlds folder and it is loaded default

**Comment by MiroTheSuperDev** [comment]
i suggest that u use a world folder named world

**Comment by drgimatt** [comment]
Ok it loaded it but how do I put Teamsign?

**Comment by MiroTheSuperDev** [comment]
check my message in your support ticket at the forums
