### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ghost** [MCrafterss/MTeamPvP#19]
[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'BudinoCraft_Team v1.0.0 Beta': Argument 1 passed to MCrafters\TeamPvP\Tasks\GameWaitingTask::__construct() must be an instance of MCrafters\TeamPvP\TeamPvP, instance of MCrafters\TeamPvP\GameManager given, called in /root/MCPE/plugins/MTeamPvP-master/src/MCrafters/TeamPvP/GameManager.php on line 24 on MCrafters\TeamPvP\TeamPvP

**Comment by AmiroEmad** [comment]
we are fixing this please wait

**Comment by iPocket** [comment]
When I get back active, I'll fix this and all other errors.

**Comment by MiroTheSuperDev** [comment]
@iPocket i am sure your inactive because of school

**Comment by iPocket** [comment]
@AmiroEmad Yes.

**Comment by NawafCraft** [comment]
Fixed I Think

**Comment by MiroTheSuperDev** [comment]
this is fixed but there is another issue that have a bug not fixed
