### ISSUE TITLE
user friendly 

### ISSUE THREAD

**Issue by MiroTheSuperDev** [MCrafterss/MTeamPvP#20]
I am making the plugin user friendly i succeded in making signs setup user friendly i might find a way to finish all this

**Comment by dries-c** [comment]
tommorow?

**Comment by MiroTheSuperDev** [comment]
@Driesboy lol not exactly tomorrow

**Comment by dries-c** [comment]
ok

**Comment by Sandertv** [comment]
Is it working already? :)

**Comment by dries-c** [comment]
no

**Comment by Sandertv** [comment]
Okie

**Comment by MiroTheSuperDev** [comment]
@sandertv it have a bug that need to be fixed it is reported in the other issue

**Comment by ghost** [comment]
I will see the problem and download the repository to fix if I can :)

**Comment by xZeroMCPE** [comment]
@AmiroEmad 
@Driesboy 

What;s wrong with this?  and what still needs to be added?

**Comment by ghost** [comment]
@AndreTheGamer Issue #17 is the cause of not working

**Comment by xZeroMCPE** [comment]
@Survingo  Ah ok.

**Comment by MiroTheSuperDev** [comment]
@AndreTheGamer we still need to add userfriendly
