### ISSUE TITLE
Add PlayerQuitEvent

### ISSUE THREAD

**Issue by ghost** [MCrafterss/MTeamPvP#23]
If a player quits from server MTeamPvP would not recognize it.
Add PlayerQuitEvent which does the same like PlayerDeathEvent, just change getEntity() to getPlayer().

**Comment by MiroTheSuperDev** [comment]
Thats combat logger right ???

**Comment by iPocket** [comment]
Nah

**Comment by MiroTheSuperDev** [comment]
i thought he means when player logs out the plugin kills him lol 

but i think he mean another thing

**Comment by iPocket** [comment]
he means it says that player quit after he quits.

**Comment by dragonwocky** [comment]
It just looks like he means that when a player leaves the server, MTeamPvP doesn't record that, it thinks the player is still online. Survingo is saying that you can use onQuitEvent() to record it so that doesn't happen....

EDIT: Oh wait now I understand what you mean @iPocket LOL

**Comment by ghost** [comment]
I don't know why I made a issue which was waiting a week that anyone other can fix that because I had no time if I fixed that in 30 seconds.... YOLO

**Comment by Sandertv** [comment]
Hehehee
