### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MiroTheSuperDev** [MCrafterss/MTeamPvP#25]
should i use this on pocketmien or genysis 

when used on genysis the config.yml is fully empty

i think you forgot to use save config function

**Comment by iPocket** [comment]
This doesn't use config, it uses config for each arena, just create an arena and you'll get a config file named as the arena name on MTeamPvP/Arena

**Comment by MiroTheSuperDev** [comment]
oops ok i will retest it now just going to get the map for the test first
