### ISSUE TITLE
kewl

### ISSUE THREAD

**Issue by ChiefArtz** [MCrafterss/MTeamPvP#3]
add mutli world support, and more items

**Comment by PocketKiller** [comment]
YOU add items on config :) also there are some bugs.. i am working on fixing them on private.

**Comment by ChiefArtz** [comment]
did u have twitter

**Comment by PocketKiller** [comment]
oops

**Comment by MaryVictoria** [comment]
work in MCPE 0.13.1?

**Comment by applqpak** [comment]
@MaryVictoria Yes.

**Comment by MaryVictoria** [comment]
ty

**Comment by applqpak** [comment]
Np

**Comment by MaryVictoria** [comment]
whats the command?cant find it

**Comment by applqpak** [comment]
Sorry for late response, but I don't think there is a command...

**Comment by MaryVictoria** [comment]
doesent.. i fond out its support only 0.12.1

**Comment by applqpak** [comment]
It works on 0.13.1, though.

**Comment by MaryVictoria** [comment]
okay.. du have a tutorial how to use this?

**Comment by applqpak** [comment]
Hang on.

**Comment by MaryVictoria** [comment]
ok

**Comment by PocketKiller** [comment]
use signs >.<

**Comment by MaryVictoria** [comment]
how? /how? the command?

**Comment by PocketKiller** [comment]
config, we made no command yet, + this is not working yet.

**Comment by MaryVictoria** [comment]
ohw..okay ty

**Comment by SleepSpace9** [comment]
When I try to join a match I get the error, that the Class "MCrafters\TeamPvP\ **GameManager** " was not found. And I also couldn't find it in the source files.

**Comment by AmiroEmad** [comment]
guys all these bugs will be fixed in less than 2 days and the plugin will be user friendly and stable
